#!/bin/sh
#
# This script use ddns-tools "dig" to retrieve public ip
# (with a redundancy on curl in case is goes missing)
# and registered ip for a freedns supplied domain
# then query the freedns endpoint to update dns in case they are not aligned

[ -z "$USERNAME" ] && echo "Missing USERNAME" >&2 && exit 1
[ -z "$PASSWORD" ] && echo "Missing PASSWORD" >&2 && exit 1
[ -z "$DOMAIN" ] && echo "Missing DOMAIN to update" >&2 && exit 1
interval_seconds=600
update_url="http://${USERNAME}:${PASSWORD}@freedns.afraid.org/nic/update?hostname=${DOMAIN}"


while :
do
  current="$(dig +short myip.opendns.com @resolver1.opendns.com)"
  current="${current:=$(curl -s https://ipecho.net/plain)}"

  registered=$(dig +short $DOMAIN)
  echo "current=$current registered=$registered"

  [ "$current" = "$registered" ] || {
    curl -s "${update_url}&myip=${current}"
    date "+DNS update on: %F %T"
  }
  unset current
  sleep "$interval_seconds"
done

